$mainMod = ALT_L
$terminal = kitty
$browser = google-chrome-stable
$fileManager = dolphin
$menu = rofi -show drun

source = ~/.config/hypr/conf.d/00-env.conf
source = ~/.config/hypr/conf.d/10-monitors.conf
source = ~/.config/hypr/conf.d/20-input.conf
source = ~/.config/hypr/conf.d/30-looknfeel.conf
source = ~/.config/hypr/conf.d/40-workspaces.conf
source = ~/.config/hypr/conf.d/50-windowrules.conf
source = ~/.config/hypr/conf.d/60-bindings.conf
source = ~/.config/hypr/conf.d/70-autostart.conf
source = ~/.config/hypr/conf.d/90-theme.conf
source = ~/.config/hypr/conf.d/99-local.conf
