env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = PATH,/home/sen/.local/share/omarchy/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin
env = OMARCHY_PATH,/home/sen/.local/share/omarchy

env = QT_QPA_PLATFORM,wayland
env = GBM_BACKEND,nvidia-drm
env = LIBVA_DRIVER_NAME,nvidia
env = NVD_BACKEND,direct
env = __EGL_VENDOR_LIBRARY_FILENAMES,/usr/share/glvnd/egl_vendor.d/10_nvidia.json
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
