input {
    kb_layout = us,ru,am
    kb_variant = ,,phonetic
    kb_options = grp:win_space_toggle
    follow_mouse = 1
    sensitivity = 0

    touchpad {
       natural_scroll = true
    }
}

gesture = 3, horizontal, workspace
