exec-once = waybar
exec-once = hyprpaper
exec-once = hypridle

exec-once = $terminal
exec-once = $browser
exec-once = slack --enable-features=UseOzonePlatform --ozone-platform=wayland
exec-once = omarchy-theme-set everforest
